"""Generate `web/contract.js` from the API's own OpenAPI schema.

The client has no build step and no type checker, so this is what stops it drifting
from the server. It is the same instinct as slice 0 of Phase 5b lifting validation
out of `cli.py`: the failure being designed against is not a crash, it is a screen
that silently renders nothing because a field was renamed and one caller still asks
for the old name.

What it emits is deliberately small -- paths, per-model field names, and the subject
states -- plus a dev-mode `expect()` that compares a response against the model the
schema says it should be and logs the difference. Not a validator, not a type
system: a named complaint in the console instead of a blank line on a screen.

Run through `agent webcontract`. It builds the app in-process and reads
`app.openapi()`, so nothing has to be listening and the schema can never be a
stale copy of one.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..config import Config
from ..gate.scheduler import Subject

HEADER = """// GENERATED by `agent webcontract`. Do not edit.
//
// Paths, response field names and the subject states, read from the API's own
// OpenAPI schema. The point is not type safety -- there is no compiler here --
// it is that a field the server stopped sending becomes a named console
// complaint rather than a blank line on a screen.
//
// Regenerate after any change to `agent/api/schemas.py` or a route signature.
// `tests/test_web_assets.py` fails when this file is out of date, so a forgotten
// regeneration is a red suite rather than a client that is quietly wrong.
"""


def _model_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _response_model(operation: dict[str, Any]) -> str | None:
    """The schema name of a 2xx JSON response, when it has one.

    A list response carries its item model, because that is the shape a caller
    checks each element against.
    """
    for code, response in (operation.get("responses") or {}).items():
        if not str(code).startswith("2"):
            continue
        schema = (
            (response.get("content") or {})
            .get("application/json", {})
            .get("schema")
        )
        if not schema:
            continue
        if "$ref" in schema:
            return _model_name(schema["$ref"])
        if schema.get("type") == "array":
            items = schema.get("items") or {}
            if "$ref" in items:
                return _model_name(items["$ref"])
    return None


def build(app: Any) -> str:
    """The contents of contract.js for this app."""
    schema = app.openapi()
    components = (schema.get("components") or {}).get("schemas") or {}

    models: dict[str, list[str]] = {}
    for name, definition in sorted(components.items()):
        properties = definition.get("properties")
        if isinstance(properties, dict):
            models[name] = sorted(properties)

    routes: dict[str, str | None] = {}
    for path, operations in sorted((schema.get("paths") or {}).items()):
        for method, operation in sorted(operations.items()):
            if method.upper() not in ("GET", "POST", "PUT", "PATCH", "DELETE"):
                continue
            routes[f"{method.upper()} {path}"] = _response_model(operation)

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    parts = [
        HEADER,
        f"\nexport const GENERATED_AT = {json.dumps(stamp)};\n",
        f"\nexport const ROUTES = {json.dumps(routes, indent=2, sort_keys=True)};\n",
        f"\nexport const MODELS = {json.dumps(models, indent=2, sort_keys=True)};\n",
        # Not in the OpenAPI schema: `state` is typed `str` there, because the
        # server returns one of these and pydantic was not asked to police it.
        # Taken from the source of truth instead, which is the property both
        # `messages._subject_line` and the API read.
        f"\nexport const SUBJECT_STATES = {json.dumps(list(Subject.STATES))};\n",
        _EXPECT,
    ]
    return "".join(parts)


_EXPECT = '''
/**
 * Compare a response body against the model the schema says it should be.
 *
 * Dev-mode only, and it never throws. A missing field is the interesting case --
 * that is the one that renders as nothing -- and an extra field is worth a
 * quieter note, because it usually means contract.js needs regenerating rather
 * than that anything is wrong.
 *
 * @param {string} route  e.g. "GET /api/now"
 * @param {unknown} body  the parsed JSON
 */
export function expect(route, body) {
  const model = ROUTES[route];
  if (!model || !MODELS[model] || body == null) return body;

  const rows = Array.isArray(body) ? body : [body];
  for (const row of rows) {
    if (row == null || typeof row !== "object") continue;
    const declared = new Set(MODELS[model]);
    const present = new Set(Object.keys(row));

    const missing = [...declared].filter((k) => !present.has(k));
    const extra = [...present].filter((k) => !declared.has(k));

    if (missing.length) {
      console.warn(
        `[contract] ${route} -> ${model} is missing: ${missing.join(", ")}` +
          " -- a screen reading one of those will render nothing."
      );
    }
    if (extra.length) {
      console.info(
        `[contract] ${route} -> ${model} has undeclared: ${extra.join(", ")}` +
          " -- run `agent webcontract`."
      );
    }
    break; // one row is enough to spot a shape change
  }
  return body;
}
'''


def write(config: Config, destination: Path) -> tuple[Path, bool]:
    """Write contract.js. Returns (path, changed).

    Compared before writing so a no-op regeneration does not touch the mtime --
    which keeps `git status` quiet and makes "is this stale" answerable by the
    test rather than by the clock.
    """
    from .app import create_app

    body = build(create_app(config))
    # The stamp changes on every run and would make every comparison differ, so
    # it is excluded from the equality that decides whether to write.
    if destination.is_file() and _without_stamp(
        destination.read_text(encoding="utf-8")
    ) == _without_stamp(body):
        return destination, False

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(body, encoding="utf-8")
    return destination, True


def _without_stamp(body: str) -> str:
    return "\n".join(
        line for line in body.splitlines() if not line.startswith("export const GENERATED_AT")
    )


# ---------------------------------------------------------------------------
# the service worker's version
# ---------------------------------------------------------------------------
#
# The shell is served cache-first, which is what makes the app open offline. The
# cost of that is that a changed app.js is invisible until the worker's cache
# name changes -- an installed PWA keeps running yesterday's code with no sign
# that it is. A hand-bumped "v1" is exactly the kind of step that gets forgotten,
# and the symptom (the fix is deployed and the phone does not have it) looks like
# the fix not working.
#
# So the version is a hash of the shell's own contents, stamped by this command,
# and `tests/test_web_assets.py` fails when a shell file changed without it.

import hashlib
import re as _re

_SHELL_LIST = _re.compile(r"const SHELL_FILES = \[(.*?)\];", _re.S)
_VERSION_LINE = _re.compile(r'^const VERSION = "[^"]*";', _re.M)


def shell_files(web_dir: Path) -> list[str]:
    """The paths sw.js precaches, as written in it."""
    body = (web_dir / "sw.js").read_text(encoding="utf-8")
    listed = _SHELL_LIST.search(body)
    if not listed:
        raise ValueError("sw.js has no SHELL_FILES array")
    return _re.findall(r'"([^"]+)"', listed.group(1))


def shell_version(web_dir: Path) -> str:
    """A short hash of every precached file's bytes, in list order.

    "/" is the app itself and is served as index.html, so it is hashed as that.
    A missing file is hashed as its name, so the version still moves when the
    list does -- and the precache test separately refuses a missing path.
    """
    digest = hashlib.sha256()
    for path in shell_files(web_dir):
        name = "index.html" if path == "/" else path.lstrip("/")
        target = web_dir / name
        digest.update(path.encode())
        digest.update(target.read_bytes() if target.is_file() else b"<missing>")
    return digest.hexdigest()[:12]


def stamp_worker(web_dir: Path) -> tuple[Path, bool]:
    """Write the shell hash into sw.js's VERSION line. Returns (path, changed)."""
    worker = web_dir / "sw.js"
    body = worker.read_text(encoding="utf-8")
    line = f'const VERSION = "{shell_version(web_dir)}";'
    if not _VERSION_LINE.search(body):
        raise ValueError("sw.js has no `const VERSION = \"...\";` line to stamp")
    updated = _VERSION_LINE.sub(line, body, count=1)
    if updated == body:
        return worker, False
    worker.write_text(updated, encoding="utf-8")
    return worker, True
