// GENERATED by `agent webcontract`. Do not edit.
//
// Paths, response field names and the subject states, read from the API's own
// OpenAPI schema. The point is not type safety -- there is no compiler here --
// it is that a field the server stopped sending becomes a named console
// complaint rather than a blank line on a screen.
//
// Regenerate after any change to `agent/api/schemas.py` or a route signature.
// `tests/test_web_assets.py` fails when this file is out of date, so a forgotten
// regeneration is a red suite rather than a client that is quietly wrong.

export const GENERATED_AT = "2026-10-02T17:42:07Z";

export const ROUTES = {
  "DELETE /api/adjustments/{adjustment_id}": "RecordedOut",
  "DELETE /api/session": "SignInOut",
  "DELETE /api/timetable/file": null,
  "GET /api/adjustments": "AdjustmentOut",
  "GET /api/deadlines": "DeadlineOut",
  "GET /api/documents/{drive_id}": "DocumentOut",
  "GET /api/documents/{drive_id}/file": null,
  "GET /api/documents/{drive_id}/position": "PositionOut",
  "GET /api/documents/{drive_id}/text": null,
  "GET /api/events": "EventOut",
  "GET /api/gate": "GateOut",
  "GET /api/health": "HealthOut",
  "GET /api/homework": "HomeworkOut",
  "GET /api/library": "LibraryPostOut",
  "GET /api/now": "NextOut",
  "GET /api/packs/{course_id}": null,
  "GET /api/projects": "ProjectOut",
  "GET /api/projects/{project_id}": "ProjectOut",
  "GET /api/quiz-attempts/{attempt_id}": "QuizAttemptOut",
  "GET /api/quizzes": "QuizzesOut",
  "GET /api/sessions": "HeldSessionOut",
  "GET /api/status": "StatusOut",
  "GET /api/study-items/{item_id}": "StudyItemOut",
  "GET /api/study-items/{item_id}/quiz": "QuizStatusOut",
  "GET /api/subjects": "SubjectOut",
  "GET /api/subjects/{name}": "SubjectOut",
  "GET /api/tasks": "TaskOut",
  "GET /api/timetable": "TimetableOut",
  "GET /api/timetable/file": null,
  "PATCH /api/timetable/file": null,
  "POST /api/adjustments": "RecordedOut",
  "POST /api/adjustments/{adjustment_id}/repoint": "RecordedOut",
  "POST /api/milestones/{milestone_id}/complete": "MilestoneOut",
  "POST /api/projects": "ProjectOut",
  "POST /api/projects/{project_id}/close": "ProjectOut",
  "POST /api/projects/{project_id}/milestones": "ProjectOut",
  "POST /api/quiz-attempts/{attempt_id}/answers": "QuizAttemptOut",
  "POST /api/quiz-attempts/{attempt_id}/flags": "QuizAttemptOut",
  "POST /api/session": "SignInOut",
  "POST /api/sessions": "HeldSessionOut",
  "POST /api/study-items/{item_id}/quiz": "QuizAttemptOut",
  "POST /api/study-items/{item_id}/quiz/request": "QuizStatusOut",
  "POST /api/study-items/{item_id}/read": "ItemActionOut",
  "POST /api/study-items/{item_id}/skip": "ItemActionOut",
  "POST /api/subjects/manual": "ManualSubjectOut",
  "POST /api/tasks": "TaskOut",
  "POST /api/tasks/{task_id}/complete": "TaskOut",
  "POST /api/timetable/file": null,
  "POST /api/uploads": null,
  "PUT /api/documents/{drive_id}/position": "PositionOut",
  "PUT /api/timetable/file": null
};

export const MODELS = {
  "AdjustmentIn": [
    "at",
    "end",
    "kind",
    "on",
    "reason",
    "room",
    "subject",
    "teacher",
    "to_date",
    "to_kind",
    "to_time"
  ],
  "AdjustmentOut": [
    "applies_on",
    "course_id",
    "created_at",
    "id",
    "kind",
    "reason",
    "session_start",
    "subject",
    "to_date",
    "to_end",
    "to_kind",
    "to_room",
    "to_start",
    "to_teacher"
  ],
  "AnswerIn": [
    "choice",
    "index"
  ],
  "Body_upload_api_uploads_post": [
    "file",
    "posted",
    "subject",
    "title"
  ],
  "DayOut": [
    "date",
    "departed",
    "exception",
    "provisional",
    "sessions",
    "version_label"
  ],
  "DeadlineOut": [
    "course_id",
    "done",
    "due_at",
    "entity_id",
    "entity_type",
    "label",
    "link",
    "links_to",
    "title"
  ],
  "DocumentOut": [
    "drive_id",
    "filename",
    "mime_type",
    "pages",
    "readable",
    "size_bytes",
    "status",
    "title",
    "url",
    "windows"
  ],
  "EventOut": [
    "course_id",
    "created_at",
    "entity_id",
    "entity_type",
    "id",
    "notified_at",
    "payload",
    "type"
  ],
  "FlagIn": [
    "index"
  ],
  "GateOut": [
    "for_date",
    "provisional",
    "sessions",
    "silent_because",
    "subjects",
    "total_items",
    "version_label",
    "worth_sending"
  ],
  "HTTPValidationError": [
    "detail"
  ],
  "HealthOut": [
    "ok"
  ],
  "HeldSessionIn": [
    "covered",
    "kind",
    "on",
    "subject"
  ],
  "HeldSessionOut": [
    "course_id",
    "course_name",
    "covered",
    "created_at",
    "held_on",
    "id",
    "kind"
  ],
  "HomeworkOut": [
    "course_id",
    "course_name",
    "done",
    "done_at",
    "due_at",
    "grade",
    "id",
    "kind",
    "late",
    "link",
    "max_points",
    "notes",
    "submission_state",
    "task_kind",
    "title"
  ],
  "ItemActionOut": [
    "item_id",
    "moved",
    "state"
  ],
  "ItemOut": [
    "alternate_link",
    "blocked_reason",
    "chars",
    "creation_time",
    "entity_id",
    "entity_type",
    "files",
    "item_id",
    "label",
    "pages",
    "ready",
    "state",
    "unread"
  ],
  "LibraryPostOut": [
    "course_id",
    "course_name",
    "creation_time",
    "documents",
    "entity_id",
    "entity_type",
    "files",
    "pages",
    "study_item_id",
    "study_item_state",
    "title",
    "unread"
  ],
  "ManualSubjectIn": [
    "subject"
  ],
  "ManualSubjectOut": [
    "already_mapped",
    "course_id",
    "created",
    "note",
    "paste",
    "subject"
  ],
  "MilestoneIn": [
    "title"
  ],
  "MilestoneOut": [
    "done_at",
    "id",
    "position",
    "title"
  ],
  "NextOut": [
    "act_in_telegram",
    "deficit",
    "files",
    "for_date",
    "item",
    "next_session",
    "silent_because",
    "subject",
    "waiting",
    "windows"
  ],
  "OrphanOut": [
    "applies_on",
    "id",
    "kind",
    "renamed_to",
    "session_start",
    "subject",
    "why"
  ],
  "PastAttemptOut": [
    "attempt_id",
    "correct",
    "counted",
    "course_id",
    "course_name",
    "finished_at",
    "item_id",
    "label",
    "passed"
  ],
  "PositionIn": [
    "page_hash",
    "page_index"
  ],
  "PositionOut": [
    "changed",
    "drive_id",
    "note",
    "page",
    "page_hash",
    "updated_at"
  ],
  "ProjectIn": [
    "brief",
    "coursework",
    "deadline",
    "deliverables",
    "milestones",
    "subject",
    "team",
    "title"
  ],
  "ProjectOut": [
    "brief_source",
    "closed_at",
    "course_id",
    "course_name",
    "coursework_id",
    "created_at",
    "deadline_at",
    "deliverables",
    "id",
    "milestones",
    "milestones_done",
    "milestones_total",
    "team",
    "title"
  ],
  "QuizAttemptOut": [
    "attempt_id",
    "course_id",
    "course_name",
    "finished",
    "finished_at",
    "index",
    "item_id",
    "label",
    "questions",
    "result",
    "started_at",
    "total"
  ],
  "QuizItemOut": [
    "course_id",
    "course_name",
    "item_id",
    "label",
    "state",
    "status"
  ],
  "QuizQuestionOut": [
    "chosen",
    "flagged",
    "index",
    "options",
    "question"
  ],
  "QuizResultOut": [
    "correct",
    "counted",
    "failures",
    "flagged",
    "needed",
    "passed",
    "review",
    "verified"
  ],
  "QuizReviewOut": [
    "chosen",
    "correct",
    "drive_id",
    "explanation",
    "flagged",
    "index",
    "options",
    "question",
    "right",
    "source_file",
    "source_page"
  ],
  "QuizStatusOut": [
    "attempt_id",
    "item_id",
    "kind",
    "reason",
    "request_outcome",
    "requested_at",
    "when"
  ],
  "QuizzesOut": [
    "attempts",
    "ready",
    "waiting"
  ],
  "RecordedOut": [
    "applies_on",
    "gate_evening",
    "gate_moves",
    "id",
    "joint_subjects",
    "kind",
    "lands_on",
    "note",
    "session_start",
    "subject",
    "written"
  ],
  "RepointIn": [
    "subject"
  ],
  "SessionOut": [
    "day",
    "end",
    "joint",
    "kind",
    "note",
    "parts",
    "start"
  ],
  "SessionPartOut": [
    "course_id",
    "room",
    "subject",
    "teacher"
  ],
  "SignInOut": [
    "expires_at",
    "signed_in"
  ],
  "SkipIn": [
    "reason"
  ],
  "StatusOut": [
    "events_pending",
    "events_total",
    "extractions",
    "last_sync",
    "ocr_errors",
    "ocr_pages",
    "schema_version",
    "sessions_live",
    "study_items",
    "telegram_bot_username"
  ],
  "StudyItemOut": [
    "course_id",
    "course_name",
    "files",
    "item",
    "item_id",
    "windows"
  ],
  "SubjectOut": [
    "blocked",
    "course_id",
    "course_name",
    "dead_files",
    "gated",
    "manual",
    "mapped_course",
    "name",
    "next_item",
    "oldest_posted_at",
    "ready",
    "sessions",
    "state",
    "unread_pages",
    "unreviewed"
  ],
  "TaskIn": [
    "due",
    "kind",
    "notes",
    "source",
    "subject",
    "title"
  ],
  "TaskOut": [
    "course_id",
    "course_name",
    "created_at",
    "done_at",
    "due_at",
    "id",
    "kind",
    "notes",
    "source",
    "title"
  ],
  "TimetableOut": [
    "days",
    "from_date",
    "orphans",
    "path",
    "subjects",
    "to_date"
  ],
  "TokenIn": [
    "token"
  ],
  "ValidationError": [
    "ctx",
    "input",
    "loc",
    "msg",
    "type"
  ],
  "WindowOut": [
    "continues",
    "first",
    "index",
    "label",
    "last",
    "pages",
    "ready",
    "snapped",
    "title",
    "topics",
    "unread",
    "unread_located"
  ]
};

export const SUBJECT_STATES = ["awaiting_course", "no_material_here", "nothing_entered", "no_readable_material", "up_to_date", "behind"];

/**
 * Compare a response body against the model the schema says it should be.
 *
 * Dev-mode only, and it never throws. A missing field is the interesting case --
 * that is the one that renders as nothing -- and an extra field is worth a
 * quieter note, because it usually means contract.js needs regenerating rather
 * than that anything is wrong.
 *
 * @param {string} route  e.g. "GET /api/now"
 * @param {unknown} body  the parsed JSON
 */
export function expect(route, body) {
  const model = ROUTES[route];
  if (!model || !MODELS[model] || body == null) return body;

  const rows = Array.isArray(body) ? body : [body];
  for (const row of rows) {
    if (row == null || typeof row !== "object") continue;
    const declared = new Set(MODELS[model]);
    const present = new Set(Object.keys(row));

    const missing = [...declared].filter((k) => !present.has(k));
    const extra = [...present].filter((k) => !declared.has(k));

    if (missing.length) {
      console.warn(
        `[contract] ${route} -> ${model} is missing: ${missing.join(", ")}` +
          " -- a screen reading one of those will render nothing."
      );
    }
    if (extra.length) {
      console.info(
        `[contract] ${route} -> ${model} has undeclared: ${extra.join(", ")}` +
          " -- run `agent webcontract`."
      );
    }
    break; // one row is enough to spot a shape change
  }
  return body;
}
